myauth/first/urls.py
from django.urls import path

from first.views import register, login_view, profile_view, logout_view, change_password, change_password_without_old_pass, user_details, dashboard_view


urlpatterns = [
    path("register/", view=register, name="register"),
    path("login/", view=login_view, name="login_view"),
    path("profile/", view=profile_view, name="profile_view"),
    path("dashboard/", view=dashboard_view, name="dashboard_view"),
    path("user-details/<int:id>/", view=user_details, name="user_details"),
    path("logout/", view=logout_view, name="logout_view"),
    path("change-password/", view=change_password, name="change_password"),
    path("change-password-1/", view=change_password_without_old_pass, name="change_password_without_old_pass"),
]

myauth/myauth/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("first.urls"))
]

myauth/first/models.py
from django.db import models


class Aohan(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=200)


class Blog(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()

myauth/first/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm



class RegisterForm(UserCreationForm):
    #!      we can change anything in password field like this only
    password2 = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")
    
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]
        
        labels = {
            "email": "Email"
        }


class EditProfileForm(UserChangeForm):
    password = None
    
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "last_login", "date_joined", "is_active"]
        
        labels = {
            "first_name": "First Name"
        }
        
        #!          not working
        # widgets = {
        #     "last_login": forms.DateTimeInput(disabled=True)
        # }


class EditAdminProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = "__all__"
        exclude = ("password",)

myauth/first/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, SetPasswordForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User, Group
from django.contrib import messages

from first.forms import RegisterForm, EditProfileForm, EditAdminProfileForm



def register(request):
    
    if request.user.is_authenticated:
        return redirect("profile_view")
    
    #NOTE :         we can do also like this
    # if request.method == "POST":
    #     form = UserCreationForm(request.POST)
        
    #     if form.is_valid():
    #         form.save()
            
    # else:
    #     form = UserCreationForm()
    
    #NOTE :         custom form edit
    if request.method == "POST":
        form = RegisterForm(request.POST)
        
        if form.is_valid():
            new_user = form.save()
            
            add_to_group = Group.objects.get(name="Editor")
            
            new_user.groups.add(add_to_group)
            
            messages.success(request, "Account Register successfully...")
            
    else:
        form = RegisterForm()
    
    context = {
        "form": form
    }
    
    return render(request=request, template_name="first/register.html", context=context)


def login_view(request):
    
    if request.user.is_authenticated:
        return redirect("profile_view")
    
    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request=request, user=user)
                
                messages.success(request, "Login success...")
                
                return redirect("profile_view")
    else:
        form = AuthenticationForm()
    
    context = {
        "form": form
    }
    
    return render(request=request, template_name="first/login.html", context=context)


def profile_view(request):
    
    if not request.user.is_authenticated:
        return redirect("login_view")
    
    if request.method == "POST":
        
        if request.user.is_superuser:
            form = EditAdminProfileForm(request.POST, instance=request.user)
        else:
            form = EditProfileForm(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, "Profile Updated...")
            
    else:
        if request.user.is_superuser:
            form = EditAdminProfileForm(instance=request.user)
        else:
            form = EditProfileForm(instance=request.user)
    
    if request.user.is_superuser:
        users = User.objects.all()
    else:
        users = None
    
    context = {
        "user_details": request.user,
        "form": form,
        "users": users
    }
    
    return render(request=request, template_name="first/profile.html", context=context)

def user_details(request, id):
    if not request.user.is_authenticated:
        return redirect("login_view")
    
    if not request.user.is_superuser:
        return redirect("profile_view")
    
    user_info = User.objects.get(pk=id)
    
    if request.method == "POST":
        form = EditAdminProfileForm(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            messages.success("Updated")
    else:
        form = EditAdminProfileForm(instance=user_info)
    
    context = {
        "user_info": user_info,
        "form": form
    }
    
    return render(request=request, template_name="first/user-details.html", context=context)


def dashboard_view(request):
    if not request.user.is_authenticated:
        return redirect("login_view")
    
    return render(request=request, template_name="first/dashboard.html")



def logout_view(request):
    if not request.user.is_authenticated:
        return redirect("login_view")
    
    logout(request=request)
    
    return redirect("login_view")


def change_password(request):
    
    if not request.user.is_authenticated:
        return redirect("login_view")
    
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, "Password updated")
            # return redirect("login_view")
            
            #!      it will not logout and update current session with new password
            update_session_auth_hash(request=request, user=form.user)
            return redirect("profile_view")
            
        
    else:
        form = PasswordChangeForm(user=request.user)
    
    context = {
        "form": form
    }
    
    return render(request=request, template_name="first/change-password.html", context=context)


def change_password_without_old_pass(request):
    
    if not request.user.is_authenticated:
        return redirect("login_view")
    
    if request.method == "POST":
        form = SetPasswordForm(user=request.user, data=request.POST)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, "Password updated")
            # return redirect("login_view")
            
            #!      it will not logout and update current session with new password
            update_session_auth_hash(request=request, user=form.user)
            return redirect("profile_view")
            
        
    else:
        form = SetPasswordForm(user=request.user)
    
    context = {
        "form": form
    }
    
    return render(request=request, template_name="first/pass-change-without-old-pass.html", context=context)

myauth/first/templates/first/change-password.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% include "header.html" %}

        <h1>Change Password With Old Password</h1>

        <form method="POST" novalidate>
            {% csrf_token %}

            <!---->
            {% if form.non_field_errors %}
            <!---->
            {% for error in form.non_field_errors %}
            <!---->
            {{ error }}
            <!---->
            {% endfor %}
            <!---->
            {% endif %}
            <!---->

            {% for field in form %}
            <!---->
            <div>{{ field.label_tag }} {{ field }} {{ field.errors }}</div>
            <!---->
            {% endfor %}

            <!---->

            <input type="submit" value="Submit" />
        </form>
    </body>
</html>

myauth/first/templates/first/dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% include "header.html" %}

        <h1>Dashboard</h1>

        <!--NOTE :  perms.app_name.action_ModelName  -->

        {% if perms.first.add_blog %}
        <button>Add</button>
        <br />
        <br />
        {% endif %}

        <!---->

        {% if perms.first.view_blog %}
        <button>View</button>
        <br />
        <br />
        {% endif %}

        <!---->

        {% if perms.first.change_blog %}
        <button>Edit</button>
        <br />
        <br />
        {% endif %}

        <!---->

        {% if perms.first.delete_blog %}
        <button>Delete</button>
        {% endif %}
    </body>
</html>

myauth/first/templates/first/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <style>
            .error {
                color: red;
            }
        </style>
    </head>
    <body>
        {% include "header.html" %}

        <h1>Login</h1>
        <form method="POST" novalidate>
            {% csrf_token %}

            <!---->

            {% if form.non_field_errors %}
            <!---->
            {% for error in form.non_field_errors %}
            <!---->
            <p class="error">{{ error }}</p>
            <!---->
            {% endfor %}
            <!---->
            {% endif %}

            <!---->

            {% for field in form %}
            <!---->
            <div>{{ field.label_tag }} {{ field }} {{ field.errors }}</div>
            <!---->
            {% endfor %}

            <input type="submit" value="Login" />
        </form>
    </body>
</html>

myauth/first/templates/first/pass-change-without-old-pass.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% include "header.html" %}

        <h1>Change Password With Old Password</h1>

        <form method="POST" novalidate>
            {% csrf_token %}

            <!---->
            {% if form.non_field_errors %}
            <!---->
            {% for error in form.non_field_errors %}
            <!---->
            {{ error }}
            <!---->
            {% endfor %}
            <!---->
            {% endif %}
            <!---->

            {% for field in form %}
            <!---->
            <div>{{ field.label_tag }} {{ field }} {{ field.errors }}</div>
            <!---->
            {% endfor %}

            <!---->

            <input type="submit" value="Submit" />
        </form>
    </body>
</html>

myauth/first/templates/first/profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% include "header.html" %}

        <h1>Profile</h1>

        <!---->
        {% if messages %}
        <!---->
        {% for message in messages %}
        <!---->
        <span>{{ message }}</span>
        <!---->
        {% endfor %}
        <!---->
        {% endif %}
        <!---->

        <p>Hello, {{ user_details.first_name }}</p>

        <h1>Update Profile Details</h1>

        <form method="POST" novalidate>
            {% csrf_token %}

            <!---->

            {% if form.non_field_errors %}
            <!---->
            {% for error in form.non_field_errors %}
            <!---->
            <span>{{ error }}</span>
            <!---->
            {% endfor %}
            <!---->
            {% endif %}
            <!---->

            {% for field in form %}
            <!---->
            <div>{{ field.label_tag }} {{ field }} {{ field.errors }}</div>
            <!---->
            {% endfor %}

            <input type="submit" value="Submit" />
        </form>

        <hr />

        <ul>
            {% for user in users %}
            <li><a href="{% url "user_details" user.id %}">{{ user.username }}</a></li>
            {% endfor %}
        </ul>
    </body>
</html>

myauth/first/templates/first/register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>

        <style>
            .success {
                color: green;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        {% include "header.html" %}

        <h1>Register</h1>
        <form method="POST" novalidate>
            {% csrf_token %}

            <!---->
            {% comment %} {{ form }} {% endcomment %}
            <!---->

            {% for field in form %}
            <!---->
            <div>{{ field.label_tag }} {{ field }} <span>{{ field.errors|striptags }}</span></div>
            <!---->
            {% endfor %}

            <input type="submit" value="Register" />
        </form>

        {% if messages %}
        <!---->
        {% for message in messages %}
        <!---->
        <!---->
        <span {% if message.tags %}class="{{ message.tags }}" {% endif %}>{{ message }}</span>
        <!---->
        {% endfor %}
        <!---->
        {% endif %}
        <!---->
        <!---->
        <!---->
    </body>
</html>

myauth/first/templates/first/user-details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <h1>{{ user_info.username }} - Details</h1>

        <form action="" method="POST">
            {% csrf_token %}

            <!---->

            {{ form }}

            <input type="submit" value="Submit" />
        </form>

        {% if messages %}
        <!---->
        {% for message in messages %}
        <span>{{ message }}</span>
        {% endfor %}
        <!---->
        {% endif %}
    </body>
</html>